services:
  raspberry:
    image: ghcr.io/nautilus-unipd/raspberry-setup@sha256:6429aec3c008a8912b52192f8f88de770518a29af2916b0648286c76b4711494
    privileged: true
    network_mode: "host"
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev
      - ./:/home/ubuntu/sensing-rigs-ros2
    group_add:
      - video
    stdin_open: true
    tty: true
    container_name: raspberry_setup

  jetson:
    image: ghcr.io/nautilus-unipd/jetson-nano-setup:latest
    privileged: true
    network_mode: "host"
    volumes:
      - ./:/home/ubuntu/sensing-rigs-ros2
    stdin_open: true
    tty: true
    container_name: jetson_setup
